import time

print('NetDNS Version: 1.0')
print('NetDNS Started ...')

file_path = "/etc/resolv.conf"
def configure_dns() :
    fh = open(file_path,"w")
    fh.write("# Generated by NetDNS [mehrab.xyz]\nnameserver 8.8.8.8\n")
    fh.close()
while True:
    file = open(file_path, "r") 
    resolv_data = file.read() 
    file.close()
    if "127.0.0.1" in resolv_data:
        configure_dns()
        print("system DNS was changed to 8.8.8.8")
    elif '8.8.8.8' in resolv_data :
        pass
    else:
        configure_dns()
        print("system DNS was changed to 8.8.8.8")
    time.sleep(5)
